name: Cleanup

on: [delete]

jobs:
  cleanup-preview-deployment:
    name: Cleanup Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Delete GitHub environment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PERSONAL_TOKEN }}
          script: |
            github.rest.repos.deleteAnEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: `preview/${process.env.GITHUB_REF_NAME}`,
            })
